
namespace sr
{
    partial class bus
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(bus));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.txtp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txtbno = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.btnreset = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnedit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnremove = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnadd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtarrival = new Bunifu.UI.WinForms.BunifuTextBox();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.txtd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtsr = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.txtp);
            this.panel1.Controls.Add(this.label6);
            this.panel1.Controls.Add(this.bunifuDataGridView1);
            this.panel1.Controls.Add(this.txtbno);
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.btnreset);
            this.panel1.Controls.Add(this.btnedit);
            this.panel1.Controls.Add(this.btnremove);
            this.panel1.Controls.Add(this.btnadd);
            this.panel1.Controls.Add(this.txtarrival);
            this.panel1.Controls.Add(this.comboBox1);
            this.panel1.Controls.Add(this.txtd);
            this.panel1.Controls.Add(this.txtsr);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Location = new System.Drawing.Point(3, 58);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(987, 414);
            this.panel1.TabIndex = 3;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // txtp
            // 
            this.txtp.AcceptsReturn = false;
            this.txtp.AcceptsTab = false;
            this.txtp.AnimationSpeed = 200;
            this.txtp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtp.BackColor = System.Drawing.Color.Transparent;
            this.txtp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtp.BackgroundImage")));
            this.txtp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtp.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtp.BorderRadius = 1;
            this.txtp.BorderThickness = 1;
            this.txtp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtp.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtp.DefaultText = "";
            this.txtp.FillColor = System.Drawing.Color.White;
            this.txtp.HideSelection = true;
            this.txtp.IconLeft = null;
            this.txtp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtp.IconPadding = 10;
            this.txtp.IconRight = null;
            this.txtp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtp.Lines = new string[0];
            this.txtp.Location = new System.Drawing.Point(334, 60);
            this.txtp.MaxLength = 32767;
            this.txtp.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtp.Modified = false;
            this.txtp.Multiline = false;
            this.txtp.Name = "txtp";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtp.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtp.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtp.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtp.OnIdleState = stateProperties4;
            this.txtp.Padding = new System.Windows.Forms.Padding(3);
            this.txtp.PasswordChar = '\0';
            this.txtp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtp.PlaceholderText = "";
            this.txtp.ReadOnly = false;
            this.txtp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtp.SelectedText = "";
            this.txtp.SelectionLength = 0;
            this.txtp.SelectionStart = 0;
            this.txtp.ShortcutsEnabled = true;
            this.txtp.Size = new System.Drawing.Size(155, 28);
            this.txtp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtp.TabIndex = 20;
            this.txtp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtp.TextMarginBottom = 0;
            this.txtp.TextMarginLeft = 3;
            this.txtp.TextMarginTop = 0;
            this.txtp.TextPlaceholder = "";
            this.txtp.UseSystemPasswordChar = false;
            this.txtp.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.SystemColors.Window;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label6.Location = new System.Drawing.Point(240, 60);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(53, 24);
            this.label6.TabIndex = 19;
            this.label6.Text = "Price";
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            this.bunifuDataGridView1.AllowUserToAddRows = false;
            this.bunifuDataGridView1.AllowUserToDeleteRows = false;
            this.bunifuDataGridView1.AllowUserToResizeColumns = false;
            this.bunifuDataGridView1.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(3, 145);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(985, 269);
            this.bunifuDataGridView1.TabIndex = 18;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bunifuDataGridView1.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridView1_CellContentClick);
            // 
            // txtbno
            // 
            this.txtbno.AcceptsReturn = false;
            this.txtbno.AcceptsTab = false;
            this.txtbno.AnimationSpeed = 200;
            this.txtbno.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbno.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbno.BackColor = System.Drawing.Color.Transparent;
            this.txtbno.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbno.BackgroundImage")));
            this.txtbno.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtbno.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtbno.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtbno.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtbno.BorderRadius = 1;
            this.txtbno.BorderThickness = 1;
            this.txtbno.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbno.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbno.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtbno.DefaultText = "";
            this.txtbno.FillColor = System.Drawing.Color.White;
            this.txtbno.HideSelection = true;
            this.txtbno.IconLeft = null;
            this.txtbno.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbno.IconPadding = 10;
            this.txtbno.IconRight = null;
            this.txtbno.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbno.Lines = new string[0];
            this.txtbno.Location = new System.Drawing.Point(82, 16);
            this.txtbno.MaxLength = 32767;
            this.txtbno.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbno.Modified = false;
            this.txtbno.Multiline = false;
            this.txtbno.Name = "txtbno";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbno.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbno.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbno.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbno.OnIdleState = stateProperties8;
            this.txtbno.Padding = new System.Windows.Forms.Padding(3);
            this.txtbno.PasswordChar = '\0';
            this.txtbno.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbno.PlaceholderText = "";
            this.txtbno.ReadOnly = false;
            this.txtbno.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbno.SelectedText = "";
            this.txtbno.SelectionLength = 0;
            this.txtbno.SelectionStart = 0;
            this.txtbno.ShortcutsEnabled = true;
            this.txtbno.Size = new System.Drawing.Size(155, 28);
            this.txtbno.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbno.TabIndex = 17;
            this.txtbno.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbno.TextMarginBottom = 0;
            this.txtbno.TextMarginLeft = 3;
            this.txtbno.TextMarginTop = 0;
            this.txtbno.TextPlaceholder = "";
            this.txtbno.UseSystemPasswordChar = false;
            this.txtbno.WordWrap = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.SystemColors.Window;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label5.Location = new System.Drawing.Point(7, 20);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(69, 24);
            this.label5.TabIndex = 16;
            this.label5.Text = "Bus no";
            // 
            // btnreset
            // 
            this.btnreset.AllowAnimations = true;
            this.btnreset.AllowMouseEffects = true;
            this.btnreset.AllowToggling = false;
            this.btnreset.AnimationSpeed = 200;
            this.btnreset.AutoGenerateColors = false;
            this.btnreset.AutoRoundBorders = false;
            this.btnreset.AutoSizeLeftIcon = true;
            this.btnreset.AutoSizeRightIcon = true;
            this.btnreset.BackColor = System.Drawing.Color.Transparent;
            this.btnreset.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnreset.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnreset.BackgroundImage")));
            this.btnreset.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.ButtonText = "Clear";
            this.btnreset.ButtonTextMarginLeft = 0;
            this.btnreset.ColorContrastOnClick = 45;
            this.btnreset.ColorContrastOnHover = 45;
            this.btnreset.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnreset.CustomizableEdges = borderEdges1;
            this.btnreset.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnreset.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnreset.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnreset.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnreset.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnreset.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnreset.ForeColor = System.Drawing.Color.White;
            this.btnreset.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnreset.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnreset.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnreset.IconMarginLeft = 11;
            this.btnreset.IconPadding = 10;
            this.btnreset.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnreset.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnreset.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnreset.IconSize = 25;
            this.btnreset.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnreset.IdleBorderRadius = 1;
            this.btnreset.IdleBorderThickness = 1;
            this.btnreset.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnreset.IdleIconLeftImage = null;
            this.btnreset.IdleIconRightImage = null;
            this.btnreset.IndicateFocus = false;
            this.btnreset.Location = new System.Drawing.Point(768, 103);
            this.btnreset.Name = "btnreset";
            this.btnreset.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnreset.OnDisabledState.BorderRadius = 1;
            this.btnreset.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.OnDisabledState.BorderThickness = 1;
            this.btnreset.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnreset.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnreset.OnDisabledState.IconLeftImage = null;
            this.btnreset.OnDisabledState.IconRightImage = null;
            this.btnreset.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnreset.onHoverState.BorderRadius = 1;
            this.btnreset.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.onHoverState.BorderThickness = 1;
            this.btnreset.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnreset.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnreset.onHoverState.IconLeftImage = null;
            this.btnreset.onHoverState.IconRightImage = null;
            this.btnreset.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnreset.OnIdleState.BorderRadius = 1;
            this.btnreset.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.OnIdleState.BorderThickness = 1;
            this.btnreset.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnreset.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnreset.OnIdleState.IconLeftImage = null;
            this.btnreset.OnIdleState.IconRightImage = null;
            this.btnreset.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnreset.OnPressedState.BorderRadius = 1;
            this.btnreset.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.OnPressedState.BorderThickness = 1;
            this.btnreset.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnreset.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnreset.OnPressedState.IconLeftImage = null;
            this.btnreset.OnPressedState.IconRightImage = null;
            this.btnreset.Size = new System.Drawing.Size(107, 36);
            this.btnreset.TabIndex = 15;
            this.btnreset.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnreset.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnreset.TextMarginLeft = 0;
            this.btnreset.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnreset.UseDefaultRadiusAndThickness = true;
            this.btnreset.Click += new System.EventHandler(this.btnreset_Click);
            // 
            // btnedit
            // 
            this.btnedit.AllowAnimations = true;
            this.btnedit.AllowMouseEffects = true;
            this.btnedit.AllowToggling = false;
            this.btnedit.AnimationSpeed = 200;
            this.btnedit.AutoGenerateColors = false;
            this.btnedit.AutoRoundBorders = false;
            this.btnedit.AutoSizeLeftIcon = true;
            this.btnedit.AutoSizeRightIcon = true;
            this.btnedit.BackColor = System.Drawing.Color.Transparent;
            this.btnedit.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnedit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnedit.BackgroundImage")));
            this.btnedit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.ButtonText = "Edit";
            this.btnedit.ButtonTextMarginLeft = 0;
            this.btnedit.ColorContrastOnClick = 45;
            this.btnedit.ColorContrastOnHover = 45;
            this.btnedit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnedit.CustomizableEdges = borderEdges2;
            this.btnedit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnedit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnedit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnedit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnedit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnedit.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnedit.ForeColor = System.Drawing.Color.White;
            this.btnedit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnedit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnedit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnedit.IconMarginLeft = 11;
            this.btnedit.IconPadding = 10;
            this.btnedit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnedit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnedit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnedit.IconSize = 25;
            this.btnedit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnedit.IdleBorderRadius = 1;
            this.btnedit.IdleBorderThickness = 1;
            this.btnedit.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnedit.IdleIconLeftImage = null;
            this.btnedit.IdleIconRightImage = null;
            this.btnedit.IndicateFocus = false;
            this.btnedit.Location = new System.Drawing.Point(312, 103);
            this.btnedit.Name = "btnedit";
            this.btnedit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnedit.OnDisabledState.BorderRadius = 1;
            this.btnedit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.OnDisabledState.BorderThickness = 1;
            this.btnedit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnedit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnedit.OnDisabledState.IconLeftImage = null;
            this.btnedit.OnDisabledState.IconRightImage = null;
            this.btnedit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnedit.onHoverState.BorderRadius = 1;
            this.btnedit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.onHoverState.BorderThickness = 1;
            this.btnedit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnedit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnedit.onHoverState.IconLeftImage = null;
            this.btnedit.onHoverState.IconRightImage = null;
            this.btnedit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnedit.OnIdleState.BorderRadius = 1;
            this.btnedit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.OnIdleState.BorderThickness = 1;
            this.btnedit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnedit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnedit.OnIdleState.IconLeftImage = null;
            this.btnedit.OnIdleState.IconRightImage = null;
            this.btnedit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnedit.OnPressedState.BorderRadius = 1;
            this.btnedit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.OnPressedState.BorderThickness = 1;
            this.btnedit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnedit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnedit.OnPressedState.IconLeftImage = null;
            this.btnedit.OnPressedState.IconRightImage = null;
            this.btnedit.Size = new System.Drawing.Size(107, 36);
            this.btnedit.TabIndex = 14;
            this.btnedit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnedit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnedit.TextMarginLeft = 0;
            this.btnedit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnedit.UseDefaultRadiusAndThickness = true;
            this.btnedit.Click += new System.EventHandler(this.btnedit_Click);
            // 
            // btnremove
            // 
            this.btnremove.AllowAnimations = true;
            this.btnremove.AllowMouseEffects = true;
            this.btnremove.AllowToggling = false;
            this.btnremove.AnimationSpeed = 200;
            this.btnremove.AutoGenerateColors = false;
            this.btnremove.AutoRoundBorders = false;
            this.btnremove.AutoSizeLeftIcon = true;
            this.btnremove.AutoSizeRightIcon = true;
            this.btnremove.BackColor = System.Drawing.Color.Transparent;
            this.btnremove.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnremove.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnremove.BackgroundImage")));
            this.btnremove.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.ButtonText = "Remove";
            this.btnremove.ButtonTextMarginLeft = 0;
            this.btnremove.ColorContrastOnClick = 45;
            this.btnremove.ColorContrastOnHover = 45;
            this.btnremove.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnremove.CustomizableEdges = borderEdges3;
            this.btnremove.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnremove.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnremove.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnremove.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnremove.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnremove.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnremove.ForeColor = System.Drawing.Color.White;
            this.btnremove.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnremove.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnremove.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnremove.IconMarginLeft = 11;
            this.btnremove.IconPadding = 10;
            this.btnremove.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnremove.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnremove.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnremove.IconSize = 25;
            this.btnremove.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnremove.IdleBorderRadius = 1;
            this.btnremove.IdleBorderThickness = 1;
            this.btnremove.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnremove.IdleIconLeftImage = null;
            this.btnremove.IdleIconRightImage = null;
            this.btnremove.IndicateFocus = false;
            this.btnremove.Location = new System.Drawing.Point(528, 103);
            this.btnremove.Name = "btnremove";
            this.btnremove.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnremove.OnDisabledState.BorderRadius = 1;
            this.btnremove.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.OnDisabledState.BorderThickness = 1;
            this.btnremove.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnremove.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnremove.OnDisabledState.IconLeftImage = null;
            this.btnremove.OnDisabledState.IconRightImage = null;
            this.btnremove.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnremove.onHoverState.BorderRadius = 1;
            this.btnremove.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.onHoverState.BorderThickness = 1;
            this.btnremove.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnremove.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnremove.onHoverState.IconLeftImage = null;
            this.btnremove.onHoverState.IconRightImage = null;
            this.btnremove.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnremove.OnIdleState.BorderRadius = 1;
            this.btnremove.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.OnIdleState.BorderThickness = 1;
            this.btnremove.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnremove.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnremove.OnIdleState.IconLeftImage = null;
            this.btnremove.OnIdleState.IconRightImage = null;
            this.btnremove.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnremove.OnPressedState.BorderRadius = 1;
            this.btnremove.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.OnPressedState.BorderThickness = 1;
            this.btnremove.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnremove.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnremove.OnPressedState.IconLeftImage = null;
            this.btnremove.OnPressedState.IconRightImage = null;
            this.btnremove.Size = new System.Drawing.Size(107, 36);
            this.btnremove.TabIndex = 13;
            this.btnremove.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnremove.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnremove.TextMarginLeft = 0;
            this.btnremove.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnremove.UseDefaultRadiusAndThickness = true;
            this.btnremove.Click += new System.EventHandler(this.btnremove_Click);
            // 
            // btnadd
            // 
            this.btnadd.AllowAnimations = true;
            this.btnadd.AllowMouseEffects = true;
            this.btnadd.AllowToggling = false;
            this.btnadd.AnimationSpeed = 200;
            this.btnadd.AutoGenerateColors = false;
            this.btnadd.AutoRoundBorders = false;
            this.btnadd.AutoSizeLeftIcon = true;
            this.btnadd.AutoSizeRightIcon = true;
            this.btnadd.BackColor = System.Drawing.Color.Transparent;
            this.btnadd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnadd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnadd.BackgroundImage")));
            this.btnadd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadd.ButtonText = "Add buses";
            this.btnadd.ButtonTextMarginLeft = 0;
            this.btnadd.ColorContrastOnClick = 45;
            this.btnadd.ColorContrastOnHover = 45;
            this.btnadd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnadd.CustomizableEdges = borderEdges4;
            this.btnadd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnadd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnadd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnadd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnadd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnadd.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnadd.ForeColor = System.Drawing.Color.White;
            this.btnadd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnadd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnadd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnadd.IconMarginLeft = 11;
            this.btnadd.IconPadding = 10;
            this.btnadd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnadd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnadd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnadd.IconSize = 25;
            this.btnadd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnadd.IdleBorderRadius = 1;
            this.btnadd.IdleBorderThickness = 1;
            this.btnadd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnadd.IdleIconLeftImage = null;
            this.btnadd.IdleIconRightImage = null;
            this.btnadd.IndicateFocus = false;
            this.btnadd.Location = new System.Drawing.Point(79, 103);
            this.btnadd.Name = "btnadd";
            this.btnadd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnadd.OnDisabledState.BorderRadius = 1;
            this.btnadd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadd.OnDisabledState.BorderThickness = 1;
            this.btnadd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnadd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnadd.OnDisabledState.IconLeftImage = null;
            this.btnadd.OnDisabledState.IconRightImage = null;
            this.btnadd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnadd.onHoverState.BorderRadius = 1;
            this.btnadd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadd.onHoverState.BorderThickness = 1;
            this.btnadd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnadd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnadd.onHoverState.IconLeftImage = null;
            this.btnadd.onHoverState.IconRightImage = null;
            this.btnadd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnadd.OnIdleState.BorderRadius = 1;
            this.btnadd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadd.OnIdleState.BorderThickness = 1;
            this.btnadd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnadd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnadd.OnIdleState.IconLeftImage = null;
            this.btnadd.OnIdleState.IconRightImage = null;
            this.btnadd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnadd.OnPressedState.BorderRadius = 1;
            this.btnadd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadd.OnPressedState.BorderThickness = 1;
            this.btnadd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnadd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnadd.OnPressedState.IconLeftImage = null;
            this.btnadd.OnPressedState.IconRightImage = null;
            this.btnadd.Size = new System.Drawing.Size(107, 36);
            this.btnadd.TabIndex = 12;
            this.btnadd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnadd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnadd.TextMarginLeft = 0;
            this.btnadd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnadd.UseDefaultRadiusAndThickness = true;
            this.btnadd.Click += new System.EventHandler(this.btnadd_Click);
            // 
            // txtarrival
            // 
            this.txtarrival.AcceptsReturn = false;
            this.txtarrival.AcceptsTab = false;
            this.txtarrival.AnimationSpeed = 200;
            this.txtarrival.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtarrival.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtarrival.BackColor = System.Drawing.Color.Transparent;
            this.txtarrival.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtarrival.BackgroundImage")));
            this.txtarrival.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtarrival.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtarrival.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtarrival.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtarrival.BorderRadius = 1;
            this.txtarrival.BorderThickness = 1;
            this.txtarrival.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtarrival.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtarrival.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtarrival.DefaultText = "";
            this.txtarrival.FillColor = System.Drawing.Color.White;
            this.txtarrival.HideSelection = true;
            this.txtarrival.IconLeft = null;
            this.txtarrival.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtarrival.IconPadding = 10;
            this.txtarrival.IconRight = null;
            this.txtarrival.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtarrival.Lines = new string[0];
            this.txtarrival.Location = new System.Drawing.Point(103, 58);
            this.txtarrival.MaxLength = 32767;
            this.txtarrival.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtarrival.Modified = false;
            this.txtarrival.Multiline = false;
            this.txtarrival.Name = "txtarrival";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtarrival.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtarrival.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtarrival.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtarrival.OnIdleState = stateProperties12;
            this.txtarrival.Padding = new System.Windows.Forms.Padding(3);
            this.txtarrival.PasswordChar = '\0';
            this.txtarrival.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtarrival.PlaceholderText = "";
            this.txtarrival.ReadOnly = false;
            this.txtarrival.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtarrival.SelectedText = "";
            this.txtarrival.SelectionLength = 0;
            this.txtarrival.SelectionStart = 0;
            this.txtarrival.ShortcutsEnabled = true;
            this.txtarrival.Size = new System.Drawing.Size(131, 26);
            this.txtarrival.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtarrival.TabIndex = 11;
            this.txtarrival.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtarrival.TextMarginBottom = 0;
            this.txtarrival.TextMarginLeft = 3;
            this.txtarrival.TextMarginTop = 0;
            this.txtarrival.TextPlaceholder = "";
            this.txtarrival.UseSystemPasswordChar = false;
            this.txtarrival.WordWrap = true;
            // 
            // comboBox1
            // 
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "Local",
            "Express",
            "Sleeper",
            "Gujjar nagari"});
            this.comboBox1.Location = new System.Drawing.Point(854, 23);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(121, 21);
            this.comboBox1.TabIndex = 10;
            this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            // 
            // txtd
            // 
            this.txtd.AcceptsReturn = false;
            this.txtd.AcceptsTab = false;
            this.txtd.AnimationSpeed = 200;
            this.txtd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtd.BackColor = System.Drawing.Color.Transparent;
            this.txtd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtd.BackgroundImage")));
            this.txtd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtd.BorderRadius = 1;
            this.txtd.BorderThickness = 1;
            this.txtd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtd.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtd.DefaultText = "";
            this.txtd.FillColor = System.Drawing.Color.White;
            this.txtd.HideSelection = true;
            this.txtd.IconLeft = null;
            this.txtd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtd.IconPadding = 10;
            this.txtd.IconRight = null;
            this.txtd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtd.Lines = new string[0];
            this.txtd.Location = new System.Drawing.Point(603, 20);
            this.txtd.MaxLength = 32767;
            this.txtd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtd.Modified = false;
            this.txtd.Multiline = false;
            this.txtd.Name = "txtd";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtd.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtd.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtd.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtd.OnIdleState = stateProperties16;
            this.txtd.Padding = new System.Windows.Forms.Padding(3);
            this.txtd.PasswordChar = '\0';
            this.txtd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtd.PlaceholderText = "";
            this.txtd.ReadOnly = false;
            this.txtd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtd.SelectedText = "";
            this.txtd.SelectionLength = 0;
            this.txtd.SelectionStart = 0;
            this.txtd.ShortcutsEnabled = true;
            this.txtd.Size = new System.Drawing.Size(155, 29);
            this.txtd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtd.TabIndex = 9;
            this.txtd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtd.TextMarginBottom = 0;
            this.txtd.TextMarginLeft = 3;
            this.txtd.TextMarginTop = 0;
            this.txtd.TextPlaceholder = "";
            this.txtd.UseSystemPasswordChar = false;
            this.txtd.WordWrap = true;
            // 
            // txtsr
            // 
            this.txtsr.AcceptsReturn = false;
            this.txtsr.AcceptsTab = false;
            this.txtsr.AnimationSpeed = 200;
            this.txtsr.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsr.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsr.BackColor = System.Drawing.Color.Transparent;
            this.txtsr.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsr.BackgroundImage")));
            this.txtsr.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtsr.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsr.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtsr.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsr.BorderRadius = 1;
            this.txtsr.BorderThickness = 1;
            this.txtsr.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsr.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsr.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtsr.DefaultText = "";
            this.txtsr.FillColor = System.Drawing.Color.White;
            this.txtsr.HideSelection = true;
            this.txtsr.IconLeft = null;
            this.txtsr.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsr.IconPadding = 10;
            this.txtsr.IconRight = null;
            this.txtsr.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsr.Lines = new string[0];
            this.txtsr.Location = new System.Drawing.Point(334, 20);
            this.txtsr.MaxLength = 32767;
            this.txtsr.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsr.Modified = false;
            this.txtsr.Multiline = false;
            this.txtsr.Name = "txtsr";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsr.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsr.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsr.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsr.OnIdleState = stateProperties20;
            this.txtsr.Padding = new System.Windows.Forms.Padding(3);
            this.txtsr.PasswordChar = '\0';
            this.txtsr.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsr.PlaceholderText = "";
            this.txtsr.ReadOnly = false;
            this.txtsr.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsr.SelectedText = "";
            this.txtsr.SelectionLength = 0;
            this.txtsr.SelectionStart = 0;
            this.txtsr.ShortcutsEnabled = true;
            this.txtsr.Size = new System.Drawing.Size(155, 28);
            this.txtsr.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsr.TabIndex = 8;
            this.txtsr.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsr.TextMarginBottom = 0;
            this.txtsr.TextMarginLeft = 3;
            this.txtsr.TextMarginTop = 0;
            this.txtsr.TextPlaceholder = "";
            this.txtsr.UseSystemPasswordChar = false;
            this.txtsr.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.SystemColors.Window;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label4.Location = new System.Drawing.Point(0, 58);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(102, 24);
            this.label4.TabIndex = 7;
            this.label4.Text = "Arrival time";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.SystemColors.Window;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label3.Location = new System.Drawing.Point(764, 20);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(82, 24);
            this.label3.TabIndex = 6;
            this.label3.Text = "Bus type";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.SystemColors.Window;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label2.Location = new System.Drawing.Point(495, 20);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(102, 24);
            this.label2.TabIndex = 5;
            this.label2.Text = "Destination";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.SystemColors.Window;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.label1.Location = new System.Drawing.Point(240, 20);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(71, 24);
            this.label1.TabIndex = 4;
            this.label1.Text = "Source";
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton2);
            this.bunifuGradientPanel1.Controls.Add(this.panel1);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.DeepPink;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(60)))), ((int)(((byte)(212)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(991, 527);
            this.bunifuGradientPanel1.TabIndex = 6;
            this.bunifuGradientPanel1.Click += new System.EventHandler(this.bunifuGradientPanel1_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Back";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges5;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(462, 478);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(104, 27);
            this.bunifuButton2.TabIndex = 5;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(353, 415);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(69, 15);
            this.bunifuLabel1.TabIndex = 7;
            this.bunifuLabel1.Text = "bunifuLabel1";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bus
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(990, 527);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "bus";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "bus";
            this.Load += new System.EventHandler(this.bus_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnreset;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnedit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnremove;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnadd;
        private System.Windows.Forms.ComboBox comboBox1;
        private Bunifu.UI.WinForms.BunifuTextBox txtd;
        private Bunifu.UI.WinForms.BunifuTextBox txtsr;
        private Bunifu.UI.WinForms.BunifuTextBox txtbno;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuTextBox txtp;
        private System.Windows.Forms.Label label6;
        public Bunifu.UI.WinForms.BunifuTextBox txtarrival;
    }
}